- name: copyModule
  hosts: tomcat
  tasks:
   - name: copying the war file.
     ansible.builtin.copy:
       src: /var/lib/jenkins/workspace/BootCamp/target/sampleapp.war
       dest: /home/ec2-user/apache-tomcat-9.0.65/webapps

        
