- name: copyModule
  hosts: tomcat
  tasks:
   - name: copying the war file.
     ansible.builtin.copy:
       src: /var/lib/jenkins/workspace/poc_integration/target
       dest: /var/lib/tomcat9/webapps
